Add Adrian Delgado as speaker in the cli week
kokoaespol/kokoa-site pull request #79
Opened 2024-11-02 03:33 UTC by alicarpio

@adriandelgado No sé cuál es tu posición en telconet, ahí revísala pls :)

2024-11-02 05:42 UTC, adriandelgado requested changes
Técnicamente no trabajo para Telconet

2024-11-02 05:42 UTC, adriandelgado commented on src/routes/events/cliweek/+page.svelte
> +			title="Pen tester @ Telconet"
```suggestion
			title="Pentester @ Syscloudsec"
```

2024-11-04 00:58 UTC, aloussase approved these changes

2024-11-04 19:47 UTC, adriandelgado approved these changes
:+1:

2024-11-04 19:48 UTC, merged